services:
  api:
    build: .
    container_name: api
    env_file:
      - .env
    ports:
      - 5001:5001
  front: 
    build: ../calc/.
    container_name: calc_front
    env_file: 
      - ../calc/.env.local
    ports: 
      - 3000:3000
    depends_on:
      - api